--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Lentou/InfoUI
build-by-default: true
branches:
- main
- master
projects:
  InfoUI:
    path: ""
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
...
