name: InfoUI
version: 1.5.0
api: 4.0.0
author: Hytlenz
main: Hytlenz\Main

commands:
  info:
    description: "shows about the server"
    permission: info.command
    
permissions:
  info.command:
    default: true
