---
# InformationUI or InfoUI by Hytlenz (Lentou)
# Supported § for color

wikipedia:
  title: "§lWikipedia"
  return: "§l< Back"
  thanks: "§aThank You for Viewing"
  content:
    - "§7Greetings, §b{player}"
    - ""
    - "§7Welcome to Wikipedia of Your Server"
    - ""
    - "§7Here you can read all"
    - "§7Informations regarding on this server"

wiki:
  about:
    button: ["About Us", ""]
    title: "About Us Title Form"
    content:
      - "You can add"
      - "More Infos as much as"
      - "You want"
  ranks:
    button: ["Ranks", "https://img2.pngio.com/ranking-png-1-png-image-ranking-png-512_512.png"]
    title: "Ranks List"
    content:
      - "Rank 1: VIP"
      - "Rank 2: MVP"
      - "Rank 3: SVP"
  others:
    button: ["Others", "textures/items/wooden_sword"]
    title: "Others"
    content:
      - "Edit the config.yml"
      - "For More Info"
# You can add more forms just follow the format.
...
